# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Tutorials
  items:
    - label: 'Chatroom App'
      link: '/tutorials/chatroom'
    - label: 'Live Video Chat (w/ WebRTC)'
      link: '/tutorials/webrtc'
    - label: 'Shadowing'
      link: '/tutorials/shadowing'
- label: Server-side Methods
  items:
    - label: '.connect'
      link: '/serverside/connect'
    - label: '.emit'
      link: '/serverside/emit'
    - label: .channel
      link: '/serverside/channel'
- label: Client-side Methods
  items:
    - label: '.directmessage'
      link: '/clientside/directMessage'
    - label: '.broadcast'
      link: '/clientside/broadcast'
    - label: .message
      link: '/clientside/message'
    - label: .changechannel
      link: '/clientside/changeChannel'
    - label: .grab
      link: '/clientside/grab'
    - label: .on
      link: '/clientside/on'
